[package]
name = "landell-wave"
version = "0.1.0"
description = "Open global internet radio directory"
authors = ["Pablo Lima"]
license = "MIT"
repository = "https://github.com/limapablo/Landell-Wave"
edition = "2021"
rust-version = "1.88"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.12", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
